version: '3'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: web.dockerfile
    depends_on: 
      - api
    tty: true
    volumes:
      - ./web:/app

  api:
    container_name: api
    build:
      context: .
      dockerfile: api.dockerfile
      args:
        - POSTGRES_DB=$POSTGRES_DB
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - POSTGRES_PORT=$POSTGRES_PORT
    depends_on: 
      - db
    tty: true
    volumes:
      - ./api:/go/app

  db:
    container_name: db
    build:
      context: .
      dockerfile: db.dockerfile
      args:
        - POSTGRES_DB=$POSTGRES_DB
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  proxy:
    container_name: proxy
    build:
      context: .
      dockerfile: proxy.dockerfile
    ports:
      - $PROXY_PORT:$PROXY_PORT
    depends_on:
      - web
